### ISSUE TITLE
Styleguide: Icons

### ISSUE THREAD

**Issue by bartmika** [MikaSoftware/inthought-react#10]
Create a page listing some fonts from latest version of font-awesome. Maybe 10 icons. Then show link at bottom of page to font awesome.

Ex: http://themicon.co/theme/angle/v4.2.2/reactjs/icons-font

**Comment by soyong20161205** [comment]
I already created this page and pushed it about 9 days ago. I pushed my code to master branch. Please QA( you might have tested that page already!)

**Comment by bartmika** [comment]
@rodolfomartinez Good to close.
