### ISSUE TITLE
Styleguide: Cards

### ISSUE THREAD

**Issue by bartmika** [MikaSoftware/inthought-react#12]
Create styleguide page dedicated to the cards.

Example 1: http://themicon.co/theme/angle/v4.2.2/reactjs/cards
Example 2: https://getbootstrap.com/docs/4.0/components/forms/

**Comment by bartmika** [comment]
Note: We have a "Settings" page that looks like this. Please make sure you implement this sort of cards as well. @rodolfomartinez FYI.

![Screen Shot 2019-03-25 at 10 08 47 PM](https://user-images.githubusercontent.com/5767602/54966422-a2433b00-4f4a-11e9-9f41-d320b1707cf0.png)

**Comment by bartmika** [comment]
Here is another example of cards. @rodolfomartinez FYI.

![Screen Shot 2019-03-25 at 10 23 11 PM](https://user-images.githubusercontent.com/5767602/54967154-049d3b00-4f4d-11e9-8989-dc9a766f7fd1.png)

**Comment by soyong20161205** [comment]
I already created this page and pushed it about 9 days ago. I pushed my code to master branch. Please QA( you might have tested that page already!)

**Comment by bartmika** [comment]
@rodolfomartinez Looks good to close!
