### ISSUE TITLE
Styleguide: Forms

### ISSUE THREAD

**Issue by bartmika** [MikaSoftware/inthought-react#13]
This is a big ticket and will require multiple sub pages. Create multiple sub-pages for different form stuff:

1. https://getbootstrap.com/docs/4.0/components/forms/
2. http://themicon.co/theme/angle/v4.2.2/reactjs/form-validation
3. http://themicon.co/theme/angle/v4.2.2/reactjs/form-wizard
4. http://themicon.co/theme/angle/v4.2.2/reactjs/form-upload

**Comment by bartmika** [comment]
# Example 1
Here are a few elements to choose from in creating a form.

![Screen Shot 2019-03-25 at 10 45 33 PM](https://user-images.githubusercontent.com/5767602/54968089-d0774980-4f4f-11e9-82be-adc8db82363d.png)

**Comment by bartmika** [comment]
@soyong20161205 Please integrate the [react-datepicker](https://reactdatepicker.com/) library with our project so our forms use this datepicker.

**Comment by soyong20161205** [comment]
yes, I added react-datepicker and do some styling so it fits in well with others.
Please QA

**Comment by bartmika** [comment]
@rodolfomartinez Good to close. I created the bug ticket in a new ticket.
