### ISSUE TITLE
Styleguide: Tables

### ISSUE THREAD

**Issue by bartmika** [MikaSoftware/inthought-react#14]
Example:
1. http://themicon.co/theme/angle/v4.2.2/reactjs/table-standard
2. http://themicon.co/theme/angle/v4.2.2/reactjs/table-extended
3. http://themicon.co/theme/angle/v4.2.2/reactjs/table-datatable
4. http://themicon.co/theme/angle/v4.2.2/reactjs/table-datagrid

**Comment by bartmika** [comment]
# Example

![Screen Shot 2019-03-25 at 10 13 49 PM](https://user-images.githubusercontent.com/5767602/54967350-b3417b80-4f4d-11e9-89a3-ed8dc89130bc.png)

**Comment by soyong20161205** [comment]
I already created this page with 2 submenus and pushed it about 9 days ago. I pushed my code to master branch. Please QA( you might have tested that page already!)

**Comment by bartmika** [comment]
@rodolfomartinez Good to close.
