### ISSUE TITLE
Styleguide: Google Maps

### ISSUE THREAD

**Issue by bartmika** [MikaSoftware/inthought-react#15]
http://themicon.co/theme/angle/v4.2.2/reactjs/map-google

**Comment by bartmika** [comment]
Please look at this link and see if you can implement something like this.

**Comment by soyong20161205** [comment]
I added google map. We can customize this map in real app. Please QA. thanks.

**Comment by bartmika** [comment]
@rodolfomartinez Looks like its working but whether Google errors is dependent on the API key settings set. I think it is good to close but we'll need to confirm w/ @soyong20161205 when we deploy.
