### ISSUE TITLE
Styleguide: Charting

### ISSUE THREAD

**Issue by bartmika** [MikaSoftware/inthought-react#16]

**Comment by bartmika** [comment]
1. Purpose a good charting library for react / javascript.
2. Create a styleguide using this library.

Ex: http://themicon.co/theme/angle/v4.2.2/reactjs/chart-flot

**Comment by soyong20161205** [comment]
I have created Chartings page and added many beautiful charts. Please QA. thanks.

**Comment by bartmika** [comment]
@rodolfomartinez Good to close.
