### ISSUE TITLE
Styleguide: List Page

### ISSUE THREAD

**Issue by bartmika** [MikaSoftware/inthought-react#17]
Inthought has a generic list page. Replicate it in the style guide as a specific page.

Example: http://themicon.co/theme/angle/v4.2.2/reactjs/ecommerce-orders

**Comment by bartmika** [comment]
# Example List Page

![Screen Shot 2019-03-25 at 10 13 06 PM](https://user-images.githubusercontent.com/5767602/54966901-13372280-4f4c-11e9-8f20-6cf1ef445098.png)

**Comment by soyong20161205** [comment]
I already created this page and pushed it about 9 days ago. I pushed my code to master branch. Please QA( you might have tested that page already!)

**Comment by bartmika** [comment]
@rodolfomartinez Good to close.
