### ISSUE TITLE
Styleguide: Details Page

### ISSUE THREAD

**Issue by bartmika** [MikaSoftware/inthought-react#18]
Inthought has a few detail pages w/ forms on there. Please create a details page in the styleguide. If some designs are so different, please create sub-pages under the 'details' category.

Ex: http://themicon.co/theme/angle/v4.2.2/reactjs/ecommerce-order-view

**Comment by soyong20161205** [comment]
I already created this page with 2 sub menus and pushed it about 9 days ago. I pushed my code to master branch. Please QA( you might have tested that page already!)

**Comment by bartmika** [comment]
@rodolfomartinez Good to close.
