### ISSUE TITLE
Styleguide: Pages

### ISSUE THREAD

**Issue by bartmika** [MikaSoftware/inthought-react#19]
There are different pages with different layout style, for example work order searching, help page, profile page. Please create pages dedicated to the them and categorize them as sub-pages for the 'page' root item in the menu.

@rodolfomartinez Please make sure @soyong20161205 creates all the pages you envision.

**Comment by bartmika** [comment]
Some extra designs which would be nice to have:
- http://themicon.co/theme/angle/v4.2.2/reactjs/invoice
- http://themicon.co/theme/angle/v4.2.2/reactjs/search
- http://themicon.co/theme/angle/v4.2.2/reactjs/settings
- http://themicon.co/theme/angle/v4.2.2/reactjs/plans
- http://themicon.co/theme/angle/v4.2.2/reactjs/help-center

**Comment by bartmika** [comment]
# Help Page

![Screen Shot 2019-03-25 at 10 11 07 PM](https://user-images.githubusercontent.com/5767602/54966550-fa7a3d00-4f4a-11e9-80aa-d280afcad094.png)

**Comment by soyong20161205** [comment]
I already created this page with 2 sub menus and pushed it about 9 days ago. I pushed my code to master branch. Please QA( you might have tested that page already!)

**Comment by bartmika** [comment]
@rodolfomartinez Good to close

**Comment by bartmika** [comment]
@rodolfomartinez Good to close
