### ISSUE TITLE
Styleguide: Wizards

### ISSUE THREAD

**Issue by bartmika** [MikaSoftware/inthought-react#20]
Create wizards menu item and create sub-pages which are designed for 1,2,3 step sort of pages that you typically find in checkout.

1. Create a page for 1,2,3 step wizard that has only one panel. Ex: See work order in inthought.
2. Create a page for 1,2,3 step wizard that has two panels. Ex: http://themicon.co/theme/angle/v4.2.2/reactjs/ecommerce-checkout

**Comment by bartmika** [comment]
# Example Wizard
![Screen Shot 2019-03-25 at 10 21 26 PM](https://user-images.githubusercontent.com/5767602/54966982-63ae8000-4f4c-11e9-9177-9dbb103166e8.png)

**Comment by soyong20161205** [comment]
I have created wizard pages. To do this, I created 2 sub menus, one for steps wizards, the other for panel. Please QA. thanks.

**Comment by bartmika** [comment]
@rodolfomartinez Good to close
