### ISSUE TITLE
Page: Comments

### ISSUE THREAD

**Issue by bartmika** [MikaSoftware/inthought-react#22]
Here is how the comments page looks like.

![Screen Shot 2019-03-25 at 10 24 31 PM](https://user-images.githubusercontent.com/5767602/54967127-ea635d00-4f4c-11e9-8762-f226b19ec385.png)

**Comment by soyong20161205** [comment]
I already created this page as a submenu item under Pages menu item and pushed it about 9 days ago. I pushed my code to master branch. Please QA( you might have tested that page already!)

**Comment by bartmika** [comment]
@rodolfomartinez Good to close
