### ISSUE TITLE
Page: Search

### ISSUE THREAD

**Issue by bartmika** [MikaSoftware/inthought-react#23]
@rodolfomartinez FYI.

# Example 1

![Screen Shot 2019-03-25 at 10 21 26 PM](https://user-images.githubusercontent.com/5767602/54967377-cd7b5980-4f4d-11e9-9f13-d9a7e39b9660.png)

# Example 2

![Screen Shot 2019-03-25 at 10 32 44 PM](https://user-images.githubusercontent.com/5767602/54967601-3bc01c00-4f4e-11e9-8bbc-2146b0313598.png)

# Example 3

![Screen Shot 2019-03-25 at 10 33 36 PM](https://user-images.githubusercontent.com/5767602/54967562-1b905d00-4f4e-11e9-9519-c05b8f05a1e6.png)

**Comment by soyong20161205** [comment]
I already created this page as a submenu item under Pages menu item and pushed it about 9 days ago. I pushed my code to master branch. Please QA( you might have tested that page already!)

**Comment by bartmika** [comment]
@rodolfomartinez Good to close
