### ISSUE TITLE
Page: Invoice

### ISSUE THREAD

**Issue by bartmika** [MikaSoftware/inthought-react#24]
http://themicon.co/theme/angle/v4.2.2/reactjs/invoice

**Comment by soyong20161205** [comment]
I have created invoice page for #24. Please QA and merge this to main branch.

**Comment by bartmika** [comment]
@rodolfomartinez Good to close

**Comment by rodolfomartinez** [comment]
Hi @soyong20161205 - just some minor changes
1. edit button - blue
2. print button - yellow
3. copy invoice button - orange

**Comment by soyong20161205** [comment]
I changed the color in branch invoice-#24,
you can merge that branch to master to see the changes.

**Comment by bartmika** [comment]
@rodolfomartinez Looks good to me! 👍
