### ISSUE TITLE
Styleguide: File Upload

### ISSUE THREAD

**Issue by bartmika** [MikaSoftware/inthought-react#25]
https://github.com/over55/workery-django/blob/master/workery/templates/tenant_customer/retrieve/for/files_view.html

**Comment by bartmika** [comment]
Please see:

* https://github.com/over55/workery-django/blob/master/workery/templates/tenant_associate/retrieve/for/files_view.html

**Comment by soyong20161205** [comment]
I can't imaging how file upload will look. And I have no idea why you need file upload in this style guide. All I can do in this style guide is just styling. So I hope you provide live link or at least screenshot of fileuploader that you are thinking of. thanks

**Comment by bartmika** [comment]
@soyong20161205 Hi Kham, could you please style it to look like this? Thanks!

![Screen Shot 2019-04-12 at 2 04 01 PM](https://user-images.githubusercontent.com/5767602/56057096-05471700-5d2c-11e9-9675-d6bc583f61e0.png)

**Comment by bartmika** [comment]
Addendum: Don't worry about the "Files", "Jobs", "Summary" navigation, just that file upload styling.

**Comment by soyong20161205** [comment]
@bartmika 
You are looking for "Files", "UPLOAD", "SAVE" BUTTON in one page.right?
what about the table?

**Comment by bartmika** [comment]
@soyong20161205 Under the "Pages" submenu, can you create a new page and call it "File Upload" and just make it look similar to the screenshot. (And remember don't include the navigation). That will be enough to close this ticket.

**Comment by soyong20161205** [comment]
@bartmika 
I have implemented the page. Please QA
