### ISSUE TITLE
Page: Register Page

### ISSUE THREAD

**Issue by bartmika** [MikaSoftware/inthought-react#3]
Create a Register page in the style guide. Also please include a "success page" when the registration was successful.

**Comment by soyong20161205** [comment]
I created Register page, pushed the page code and created pull request. Please merge my work and QA. Thanks.

**Comment by bartmika** [comment]
@rodolfomartinez Good for closing.

**Comment by rodolfomartinez** [comment]
@bartmika - what about JSON country/province matcher? Or is this a validation ticket?

**Comment by bartmika** [comment]
@rodolfomartinez I think we might be good with the province / country validation because we will be using a different library called [react-select](https://github.com/JedWatson/react-select) to populate those fields. Afterwords we will try to use that library to make API calls for country specific provinces once the country was selected.

For validation, I believe I have an issue related to border colour which is affecting this register page.
