### ISSUE TITLE
React Multi Series Area Chart - Not Working

### ISSUE THREAD

**Issue by bartmika** [MikaSoftware/inthought-react#32]
Just deployed the latest code to https://inthought.mikaponics.com and I see the ``React Multi Series Area Chart``. Could you fix?

![Screen Shot 2019-04-09 at 11 23 33 PM](https://user-images.githubusercontent.com/5767602/55849534-f2132c00-5b1e-11e9-9c9b-696a5d9f37bd.png)

**Comment by bartmika** [comment]
Note: This bug was found in Apple Safari browser, it is confirmed working in Google Chrome.

**Comment by soyong20161205** [comment]
@bartmika 
Problem is that safari on iPhone/iPad doesn’t support dateString format.
I fixed this issue. please try and let me know if it works.
You can check branch Charting-#16

**Comment by rodolfomartinez** [comment]
@bartmika - you understand this error best - please QA and close when you feel ready.

**Comment by bartmika** [comment]
@rodolfomartinez Looks good to me! 👍
