### ISSUE TITLE
Google Maps - Developer Mode?

### ISSUE THREAD

**Issue by bartmika** [MikaSoftware/inthought-react#33]
Hi @soyong20161205 , could you provide more details on this error? I think this might actually be working but requires somesort of Google API setup modifications. In any case if you could provide some details on this issue that would be great!

![Screen Shot 2019-04-09 at 11 24 37 PM](https://user-images.githubusercontent.com/5767602/55849614-47e7d400-5b1f-11e9-9c71-c650ff5a2e4d.png)

**Comment by soyong20161205** [comment]
When you develop app, you can simply substitute with your google map API key.
Since I am currently using API which is not enabled billing, the map is watered marked and dark, also pops up alert message.
If you use your own correct API keys, this should work properly.

**Comment by bartmika** [comment]
Okay understood
