### ISSUE TITLE
Form - Border Colour

### ISSUE THREAD

**Issue by bartmika** [MikaSoftware/inthought-react#34]
![Screen Shot 2019-04-09 at 11 32 23 PM](https://user-images.githubusercontent.com/5767602/55849787-d8beaf80-5b1f-11e9-8706-e7d0b68fff6d.png)

Could you update the form validation page to demonstrate how to handle the ``border color`` when a form item is either required (blue) or optional (green) and how the form ``boarder color`` changes to green on success and ``red`` on error.

**Comment by soyong20161205** [comment]
@bartmika, so you want to make the border of input field highlight with green, or blue or red according to the validation status, right? 
currently the border is highlighted with thin green or blue color, do you want it thick?

**Comment by bartmika** [comment]
@soyong20161205 the inthought theme rules are as follows:

# before validation
1. If set className was “primary” then it’s blue and it means this field is required
2. If set className was “success” then it’s green and it means this field is optional

# after validation
1. If the field was validated as success the className is set to success which will make the field in green.
2. If the field was validated as error then the className is set to error which makes the field in red and the error messsge underneath the field.

# note
I have this useful code if you wanna use
https://github.com/mikaponics/mikaponics-front/blob/master/src/components/bootstrap/bootstrapInput.js

**Comment by bartmika** [comment]
@soyong20161205 Note: I am currently trying to integrate validation for input fields but it's missing the primary or success colour when we want the field to be required/option. Take a look at our code:

https://github.com/mikaponics/mikaponics-front via https://app.mikaponics.com
https://github.com/mikaponics/mikaponics-back via https://api.mikaponics.com

**Comment by soyong20161205** [comment]
I can see that validation function is already working properly in this site, except that border color is missing.

Please use this;

simply add "... border-primary" or "... border-success" to className of input field. These classes are already out there out of box.

![border-color-1](https://user-images.githubusercontent.com/40175691/56020062-6ffa5180-5d30-11e9-8ddf-97523e5441f6.jpg)

**Comment by bartmika** [comment]
@soyong20161205 Hi Kham, I tried that but my problem is that the blue border remains after the validation. Here is the picture.

![Screen Shot 2019-04-12 at 2 27 38 PM](https://user-images.githubusercontent.com/5767602/56058394-4f7dc780-5d2f-11e9-8c30-47f0e33e82c5.png)

I will grant you **contributor** access to the [mikaponics-front](https://github.com/mikaponics/mikaponics-front) so you may modify if possible. The code which controls adding the border colours is in here: https://github.com/mikaponics/mikaponics-front/blob/master/src/components/bootstrap/bootstrapInput.js

**Comment by bartmika** [comment]
@soyong20161205 Never mind, I figured it out! Thanks for your help, I am closing this issue. 🥇
