### ISSUE TITLE
Long Table Column - Bug

### ISSUE THREAD

**Issue by bartmika** [MikaSoftware/inthought-react#35]
@soyong20161205 I implemented these code and used the code from the table which has a long column name ("Number of devices purchasing") and the table looks as follows. Do you know a good fix to the CSS so this won't happen in the future?

![Screen Shot 2019-04-05 at 1 13 14 AM](https://user-images.githubusercontent.com/5767602/55851626-6b168180-5b27-11e9-99bb-104e1c2de54d.png)

**Comment by soyong20161205** [comment]
so what do you want it to look like?

**Comment by soyong20161205** [comment]
@bartmika 
I need some rule for portioning. for example, by default, left column should be 30%. And if the string is long, the column should extend accordingly.

Also to fix this bug, I need to check the page source.

**Comment by bartmika** [comment]
Page source via https://github.com/mikaponics/mikaponics-front/blob/master/src/components/onboarding/onboardCheckoutComponent.js

**Comment by bartmika** [comment]
@soyong20161205 can you write something which is automatic and requires any worry from someone using this GUI library?

**Comment by soyong20161205** [comment]
It's weird. Currently in your page, 
"table.custom-cell-w tr th " css styling is not working, though it is existing in your source code like this
<table className="**table table-bordered custom-cell-w**">
                                <tbody>
                                    <tr className="bg-dark">
...

I just tried it myself, if I remove this className or remove the style in css file, it proves to be the same as you.

I can check it in  your project for you if you wish.

**Comment by bartmika** [comment]
@soyong20161205 wait on fixing the mikaponics-front project just yet b/c I haven’t deployed the latest mikaponics-back. Try finishing the other tickets and we can revisit this last.

**Comment by bartmika** [comment]
@soyong20161205 Hi Kham, I redeployed the latest code which is integrating this library. The two projects are and their (QA) website links are:

* https://github.com/mikaponics/mikaponics-front via https://app.mikaponics.com
* https://github.com/mikaponics/mikaponics-back via https://api.mikaponics.com

Please have a look to see if you can get to the root of the problem. Also it's important to note the API server is running QA mode so don't be afraid to put in junk data.

**Comment by soyong20161205** [comment]
![table-cell-issue](https://user-images.githubusercontent.com/40175691/56017750-72f24380-5d2a-11e9-8e58-aa6cddbf6f64.jpg)
![table-cell-issue2](https://user-images.githubusercontent.com/40175691/56017904-c5336480-5d2a-11e9-859b-9000f7417596.jpg)

**Comment by soyong20161205** [comment]
as you can see from two images above, the following style is missing;
table.custom-cell-w tr th {
    width: 35% !important;
}

We need to add this style to your project. To do this, please copy and paste /public/assets/css/base.css from my project to yours

**Comment by soyong20161205** [comment]
Ah, I just noticed, when the page is first loaded, the style was working, but when I refresh the page, it is not loading base.css, and the style breaks.
![table-cell-issue3](https://user-images.githubusercontent.com/40175691/56018635-dc735180-5d2c-11e9-8bab-fa76fdbf03b6.jpg)
![table-cell-issue4](https://user-images.githubusercontent.com/40175691/56018636-dc735180-5d2c-11e9-983d-05cc52b4b0cc.jpg)

**Comment by soyong20161205** [comment]
I think it probably has something to do with loading path of css.
There are some articles about it over internet like
https://stackoverflow.com/questions/22631158/resource-interpreted-as-stylesheet-but-transferred-with-mime-type-text-html-see
https://stackoverflow.com/questions/41734976/resource-interpreted-as-stylesheet-but-transferred-with-mime-type-text-javascrip/41851906

Since I don't have access to your project, I can't fix it directly.

**Comment by soyong20161205** [comment]
after investigating further, I found out the path to base.css changed between first load of page and the second one.
Please check out the following snapshots
![table-cell-issue5](https://user-images.githubusercontent.com/40175691/56019272-67088080-5d2e-11e9-97f2-9386919c2678.jpg)
![table-cell-issue6](https://user-images.githubusercontent.com/40175691/56019273-67088080-5d2e-11e9-9369-6fde4910d0d2.jpg)

. you need to fix this;

**Comment by bartmika** [comment]
@soyong20161205 Thank you Kham for your explanation! This helped me fix the problem. I consider this issue closed.
