### ISSUE TITLE
Styleguide: Top Menu

### ISSUE THREAD

**Issue by bartmika** [MikaSoftware/inthought-react#4]
Create a page in the styleguide with code snippets for different top menu.

**Comment by bartmika** [comment]
@rodolfomartinez What I was thinking here is if we can have a few code samples on the page which show different navigation styles. For example, one just has a hamburger icon, another example includes notification bell, another example has inbox icon, another example has a search field.

**Comment by soyong20161205** [comment]
I created top menu. Please merge Top-Menu-#4 branch which I created. Please QA
