### ISSUE TITLE
Consistency in Code

### ISSUE THREAD

**Issue by bartmika** [MikaSoftware/inthought-react#40]
# Issue
1. In [this file](https://github.com/MikaSoftware/inthought-react/blob/master/src/components/Tables/Table2.js) I noticed the following code:

    ```html
    <main id="main" role="main">
    ```

2. But when I looked in [this file](https://github.com/MikaSoftware/inthought-react/blob/master/src/components/Tables/Table1.js) I noticed that ``<main>`` element was not there.

3. Also I noticed in [dashboard file]() that we have the following code but not in the above files:

    ```html
    <div className="container">
    ```

# Task
@soyong20161205 May you please bring some code consistency with your ``HTML`` elements for all the pages? I want all the pages to be consistent.

**Comment by soyong20161205** [comment]
I fixed all pages so they follow the same structure. Please QA

**Comment by bartmika** [comment]
Confirmed
