### ISSUE TITLE
Page Margins

### ISSUE THREAD

**Issue by bartmika** [MikaSoftware/inthought-react#41]
@soyong20161205 Hi Kham, I am having difficulty with page margins. For example this is what I see in the  [mikaponics-front](https://github.com/mikaponics/mikaponics-front) project I am working on.

![Screen Shot 2019-04-13 at 10 27 02 PM](https://user-images.githubusercontent.com/5767602/56087632-06b43480-5e3d-11e9-8d01-f8cb0a5c7202.png)

However in the theme I see we have these. See this picture.

![Screen Shot 2019-04-13 at 10 37 37 PM](https://user-images.githubusercontent.com/5767602/56087636-1469ba00-5e3d-11e9-87a7-7db20fd2617a.png)

I had some difficulty with the page margins, perhaps this is related to issue #40 but I'd like your assist. I am using this theme in the [mikaponics-front](https://github.com/mikaponics/mikaponics-front) repo.

**Comment by soyong20161205** [comment]
![Screenshot_2](https://user-images.githubusercontent.com/40175691/56087897-d604e700-5e9e-11e9-915f-6dbeb28c8991.jpg)
which one do you want? I need more detailed question

**Comment by bartmika** [comment]
@soyong20161205
