### ISSUE TITLE
iPhone 6 Broken GUI 

### ISSUE THREAD

**Issue by bartmika** [MikaSoftware/inthought-react#45]
![D7596511-17D2-4659-839A-07A6D66B69BE](https://user-images.githubusercontent.com/5767602/56097707-14fa6300-5ec6-11e9-9a29-010d1015a88e.jpeg)

I tried loading theme on iPhone 6 and i see above. Please fix the two issues.

**Comment by soyong20161205** [comment]
@bartmika 
fixed, please merge branch - "#47,#45" and test it.
