### ISSUE TITLE
Integrate with "react-burger-menu" library

### ISSUE THREAD

**Issue by bartmika** [MikaSoftware/inthought-react#46]
We want to start removing as much of the jquery and other libraries as possible so we are using as much of react as possible or third party libraries from ``NPM``.

Please change the menu to be powered by the [react-burger-menu](https://github.com/negomi/react-burger-menu).

@rodolfomartinez FYI

**Comment by bartmika** [comment]
@soyong20161205 FYI I have integrated the project with the mikaponics repository. You can see what I got working https://github.com/mikaponics/mikaponics-front/commit/3f81bd4cac8b3e2f435d055de2acb8e72ce66023

I do need help for styling the side menu.

**Comment by bartmika** [comment]
Here is what I have.

![Screen Shot 2019-04-14 at 8 17 49 PM](https://user-images.githubusercontent.com/5767602/56101521-8819ce80-5ef2-11e9-8960-79e1ec3bb236.png)

**Comment by bartmika** [comment]
@soyong20161205 Good news, the functionality has been implemented, only thing left is figuring out styling. These files will be major help:

* https://github.com/mikaponics/mikaponics-front/blob/master/src/components/navigation/topMenuComponent.js

*  https://github.com/mikaponics/mikaponics-front/blob/master/src/components/navigation/hamburger-menu.css

* https://github.com/mikaponics/mikaponics-front/blob/master/src/containers/navigation/topMenuContainer.js

**Comment by soyong20161205** [comment]
when I remove jquery and use standard react packages, do I need to implement them to  mikaponics/mikaponics-front? or styleguide project?

**Comment by bartmika** [comment]
@soyong20161205 You only need to implement it in the style guide project. Just update the ``readme.md`` file that you need this library.

**Comment by bartmika** [comment]
@soyong20161205 Sorry I accidentally closed it. Basically once you implement this ``react-hamburger-menu`` library into our project, I'll close this ticket.

**Comment by bartmika** [comment]
![Screen Shot 2019-04-17 at 10 28 41 PM](https://user-images.githubusercontent.com/5767602/56332942-39716c00-6160-11e9-8a4a-744d5e8808f7.png)

Your most recent CSS fixes got us closer to fixing the issue. Here is what the GUI looks like, now we just need to figure out how to make the transparent black overlay to be the whole screen and the navigation bar to be on-par with the top menu. If you can figure this out and implement it in the inthought library, that would be great!

**Comment by soyong20161205** [comment]
I have removed all custom scripts like base.js and custom.js.
I also implemented sideMenu and burger menu button without using third party libraries, Please check out styleguide project. I have pushed my code to branch "#46,#49".

**Comment by soyong20161205** [comment]
@bartmika 
I have removed all custom scripts like base.js and custom.js.
I also implemented sideMenu and burger menu button without using third party libraries, Please check out styleguide project. I have pushed my code to branch "#46,#49".

**Comment by bartmika** [comment]
@soyong20161205 I have found a bug with your code in the ``inthought`` theme. When I click the menu item (1) I then click the form (2) but the menu does not disappear (3). 

![Screen Shot 2019-04-19 at 12 57 27 PM](https://user-images.githubusercontent.com/5767602/56434530-ece27980-62a2-11e9-83f7-10ff99e14858.png)

May you please fix ASAP?

**Comment by soyong20161205** [comment]
@bartmika 
have you integrated the latest changes? On which url can i see the bug?

**Comment by bartmika** [comment]
@soyong20161205 Take a look here: https://inthought.mikaponics.com/FormElements

In general, we want the menu to disappear when you click outside of the menu. Let me give you an example, notice how the menu disappears here https://app.mikaponics.com/ because the ``react-hamburger-menu`` library creates an "overlay" that when you click will cause the menu to close.

**Comment by bartmika** [comment]
@soyong20161205 Btw, great job with the custom menu. Just fix this bug and I'll close this issue. However, if you run into difficulties, feel free to implement the ``react-hamburger-menu`` library. Thanks!

**Comment by soyong20161205** [comment]
Not a big deal, actually, will implement soon

**Comment by soyong20161205** [comment]
of course I can customize react-hamburger-menu with styling, but to be frank, it is not looking better and easier to customize than existing one

**Comment by bartmika** [comment]
@soyong20161205 Okay understood. I'll wait for your bugfix and we'll go with your custom menu solution then.

**Comment by soyong20161205** [comment]
@bartmika 
I think I have done this task, please merge my branch ( #46) and check it out.

**Comment by bartmika** [comment]
@soyong20161205 Fix confirmed
