### ISSUE TITLE
Hamburger Icon a little big?

### ISSUE THREAD

**Issue by bartmika** [MikaSoftware/inthought-react#47]
The hamburger icon is not symmetric, can you look into this?

![Screen Shot 2019-04-14 at 6 59 11 PM](https://user-images.githubusercontent.com/5767602/56100518-944c5e80-5ee7-11e9-8b49-f798d9a057a2.png)

**Comment by soyong20161205** [comment]
@bartmika 
fixed, please merge new branch - "#47,#45"
