### ISSUE TITLE
Password & Password Repeat in registration

### ISSUE THREAD

**Issue by bartmika** [MikaSoftware/inthought-react#48]
The [forms](https://inthought.mikaponics.com/RegisterPage) page is missing ``password`` and ``password repeat`` field. Please implement and confirm the code works with  browser``Autofill` suggest password and the browser fills in both fields.

**Comment by soyong20161205** [comment]
please explain in more details about browser's autofill suggest password

**Comment by bartmika** [comment]
We are trying to get this feature working with the theme:

https://www.bleepingcomputer.com/tips/web-browsers/google-chrome-has-a-built-in-password-generator-heres-how-to-use-it/

So when we click the password field, chrome says it can generate a password, but when it does, it did not generate a password for the second field. Need to figure out what’s going on.

**Comment by bartmika** [comment]
* https://github.com/mikaponics/mikaponics-front/blob/master/src/components/account/registerComponent.js

* https://github.com/mikaponics/mikaponics-front/blob/master/src/components/bootstrap/bootstrapInput.js

**Comment by bartmika** [comment]
@soyong20161205 I think I figured this out. Closing issue.
