### ISSUE TITLE
Remove javascript in public/index.html

### ISSUE THREAD

**Issue by bartmika** [MikaSoftware/inthought-react#49]
I have successfully removed the javascript from the [public/index.html](https://github.com/mikaponics/mikaponics-front/blob/master/public/index.html) file and utilized ``npm`` to load up our libraries that we require.

I would like you to remove all the third-party javascript libraries from the index.html and use the ``npm``.

**Comment by soyong20161205** [comment]
@bartmika 
when I remove jquery and use standard react packages, do I need to implement them to  mikaponics/mikaponics-front? or styleguide project?

**Comment by bartmika** [comment]
@soyong20161205 Hi Kham, no don't worry about it. Just update the ``readme.md`` file letting us know what libraries we need to install to use this repo.

**Comment by soyong20161205** [comment]
@bartmika 
I have removed all custom scripts like base.js and custom.js.
I also implemented sideMenu and burger menu button without using third party libraries, Please check out styleguide project. I have pushed my code to branch "#46,#49".
