### ISSUE TITLE
Integrate "recharts" library 

### ISSUE THREAD

**Issue by bartmika** [MikaSoftware/inthought-react#53]
The [charting page](https://inthought.mikaponics.com/Charting) looks good with the [CanvasJSChart](https://canvasjs.com/) library; however, some clients we work with will not want to use software you have to pay, as a result we need to have an alternative.

May you please make the charting page we currently have and put it in a "convasjs" sub-page and create another subpage and call it "recharts".

Afterwords on this "recharts" sub-page, please create a few graphs powered by the [recharts](http://recharts.org/en-US/) library. Please keep in mind we will need **time-series data** graphs as well.

To help you out, I have working code here:

* https://github.com/mikaponics/mikaponics-front/blob/master/src/components/instruments/instrumentDataComponent.js

And here is how it looks like when rendered with sample data:

![Screen Shot 2019-04-20 at 12 44 04 AM](https://user-images.githubusercontent.com/5767602/56452859-7aef4c00-6305-11e9-908e-5bcfa1562c79.png)

@rodolfomartinez FYI this ticket.

**Comment by bartmika** [comment]
Another cool example of time-series data being rendered with this library.

![Screen Shot 2019-04-22 at 10 31 15 PM](https://user-images.githubusercontent.com/5767602/56548651-9ef19e00-654e-11e9-8768-676ad111f052.png)

**Comment by soyong20161205** [comment]
I will check it, thanks.

**Comment by soyong20161205** [comment]
@bartmika 
I have done this task, please merge brach and check it out. thanks.

**Comment by bartmika** [comment]
@soyong20161205 Looks good!
