### ISSUE TITLE
Login Page - size of buttons & Fields?

### ISSUE THREAD

**Issue by rodolfomartinez** [MikaSoftware/inthought-react#56]
**Summary:**
on the login page, the fields and login buttons, as well as the green notification seem really long.  They are OK on mobile, but way too big on 1080p. See attached screen cap
![2019-04-24](https://user-images.githubusercontent.com/7537946/56627817-68cb2180-6615-11e9-92fe-a442fc2d5388.png)

**Comment by soyong20161205** [comment]
@rodolfomartinez 
Can you come online on skype so I need to discuss things with you?
