### ISSUE TITLE
Update logo images

### ISSUE THREAD

**Issue by bartmika** [MikaSoftware/inthought-react#57]
@soyong20161205 Please go through the theme and remove all the "over55" logos and replace them with the following icon. Pick the best icons for the pages.

# Image 1
(Note: This image is a transparent background with white logo)
![inthought logo white](https://user-images.githubusercontent.com/5767602/56628274-2e628400-6617-11e9-8956-736ea6981b26.png)

# Image 2
![inthought logo black](https://user-images.githubusercontent.com/5767602/56628282-34f0fb80-6617-11e9-8edb-e8d53fd5012f.png)

**Comment by soyong20161205** [comment]
@bartmika 
I've done this job and created new branch.
