### ISSUE TITLE
Integrate with "Pace.js" third party library

### ISSUE THREAD

**Issue by bartmika** [MikaSoftware/inthought-react#69]
I followed [this article](https://medium.com/@andelhusbands/make-react-router-navigation-feel-smoother-using-css-and-pace-js-13f3e22a4595) and successfully installed the page loader animation. Please add support for the [Pace.js](https://github.com/HubSpot/pace) library with our theme.

If you want to see how I implemented with the ``mikaponics-front`` project, [here is my code](https://github.com/mikaponics/mikaponics-front/commit/df466c4e150c4818f3584932d94b84dc3f9ffcec).

**Comment by soyong20161205** [comment]
@bartmika 
I integrated pace.js. Please check out pull request and test it. thanks.
