### ISSUE TITLE
Add "Modal" section

### ISSUE THREAD

**Issue by bartmika** [MikaSoftware/inthought-react#71]
@soyong20161205 Hi Kham, can you please create a new page in the theme which has "modals"? 

1. Can you have one button which will trigger a modal that cannot be closed until a button in the modal is closed

2. Can you have one button which will trigger a modal that can be closed if you click the anywhere outside the modal?

3. Can you have a few different designs for us to choose from for the modals? I'll let you choose the designs after you've done your research on stuff we can do.

Thanks!

**Comment by soyong20161205** [comment]
@bartmika 
i have gathered react modals, please check the following links and let me know which one to go with.

https://react-bootstrap.github.io/components/modal/
https://codepen.io/claydiffrient/pen/ZBmyKz
http://www.qimingweng.com/react-modal-dialog/

**Comment by bartmika** [comment]
@soyong20161205 Please create sub-page for this library https://codepen.io/claydiffrient/pen/ZBmyKz in the modals parent page. The others look great put I am unsure at the moment.
