### ISSUE TITLE
Clean up warnings

### ISSUE THREAD

**Issue by bartmika** [MikaSoftware/inthought-react#76]
Hi @soyong20161205 , could you clean up the code so these warnings disappear when I run ``npm start`` ? Thanks!

![Screen Shot 2019-05-19 at 11 50 23 AM](https://user-images.githubusercontent.com/5767602/57984709-7913c800-7a2c-11e9-98bd-c743d37bbea8.png)

**Comment by soyong20161205** [comment]
I have just cleaned up the warnings.
