### ISSUE TITLE
Add pagination to list

### ISSUE THREAD

**Issue by bartmika** [MikaSoftware/inthought-react#82]
Hi @soyong20161205, can you add pagination to the table list page?

https://inthought.mikaponics.com/Table2

**Comment by bartmika** [comment]
@soyong20161205 Hi Kham, this is good, but I noticed you replaced ``Table2.js`` with the latest changes. I was hoping you leave ``Table2.js`` as it was previously and add your recent code in a new file called ``Table3.js``.

**Comment by soyong20161205** [comment]
I have just revised the table2 and added the table3.
