### ISSUE TITLE
Integrate third party library "react-dropzone"

### ISSUE THREAD

**Issue by bartmika** [MikaSoftware/inthought-react#86]
@soyong20161205 Please create a page called "dropzone" under forms and please show GUI element of usage for the [react-dropzone](https://github.com/react-dropzone/react-dropzone) library.

**Comment by bartmika** [comment]
![Screen Shot 2019-06-07 at 4 37 16 PM](https://user-images.githubusercontent.com/5767602/59132210-90b2e200-8942-11e9-8362-524168cd49b7.png)

Can you make sure the dropzone will work with the current form and have a preview when you upload something? Here's a screenshot of what I got working but I need help w/ the proper styling.

**Comment by soyong20161205** [comment]
I have just integrated the third party library "react-dropzone" -
tickect#86.
